spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Diksha123
    url: jdbc:mysql://localhost:3306/jrtp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: 
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 7080    
